### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by davidzwb** [nminoru/pg_plan_tree_dot#1]
when doing a make, occures an error, saying:

cc1plus: warning: command line option ‘-Wmissing-prototypes’ is valid for C/ObjC but not for C++
cc1plus: warning: command line option ‘-Wdeclaration-after-statement’ is valid for C/ObjC but not for C++
cc1plus: sorry, unimplemented: -fexcess-precision=standard for C++
Makefile:22: recipe for target 'plan_tree_view.o' failed
make: **\* [plan_tree_view.o] Error 1

is it my compiler config problem? i'm using 5.4.0 20160609, ubuntu, postgres 9.6rc1.

**Comment by nminoru** [comment]
@davidzwb
Thank you for your information.

I try to fix the error by commit 8076cd4
Please check if it works.

**Comment by davidzwb** [comment]
Thanks, it works perfectly, the result plan picture is so beautiful.

but just for your information, i met the following one single warning during compiling:

> plan_tree_view.cpp: In member function ‘void NodeInfoEnv::append(const char*, ...)’:
> plan_tree_view.cpp:205:24: warning: function might be possible candidate for ‘gnu_printf’ format attribute [-Wsuggest-attribute=format]
>    vsprintf(buf, fmt, ap);
